apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-deployment
  namespace: app-namespace
  labels:
    app: boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot 
    spec:
      containers:
      - name: bootstrap-cont
        image: magdy79/boots
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: boot-service
  namespace: jenkins-namespace
spec:
  selector:
    app: boot 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
