apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-deployment
  namespace: jenkins-namespace
  labels:
    app: boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot 
    spec:
      containers:
      - name: magdy79/boot
        image: magdy79/boot
        ports:
        - containerPort: 5000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: boot-service
  namespace: jenkins-namespace
spec:
  selector:
    app: boot 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31110